name: Rust CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Show Rust version
        run: rustc --version

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose