name: Rust CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: parser

    steps:
      - uses: actions/checkout@v5
      - run: cargo test